package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class UserTokenDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.user_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.app_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.token
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.expire_time
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Integer expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.valid
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.gmt_create
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userToken.gmt_modified
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.user_id
     *
     * @return the value of userToken.user_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.user_id
     *
     * @param userId the value for userToken.user_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.app_id
     *
     * @return the value of userToken.app_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.app_id
     *
     * @param appId the value for userToken.app_id
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.token
     *
     * @return the value of userToken.token
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.token
     *
     * @param token the value for userToken.token
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.expire_time
     *
     * @return the value of userToken.expire_time
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.expire_time
     *
     * @param expireTime the value for userToken.expire_time
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.valid
     *
     * @return the value of userToken.valid
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.valid
     *
     * @param valid the value for userToken.valid
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.gmt_create
     *
     * @return the value of userToken.gmt_create
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.gmt_create
     *
     * @param gmtCreate the value for userToken.gmt_create
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userToken.gmt_modified
     *
     * @return the value of userToken.gmt_modified
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userToken.gmt_modified
     *
     * @param gmtModified the value for userToken.gmt_modified
     *
     * @mbg.generated Thu Feb 13 19:08:40 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}