package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class FundDataDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.unit_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double unitNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.accumulated_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double accumulatedNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.growth_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double growthRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1w
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate1w;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate1m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_3m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate3m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_6m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate6m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate1y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_2y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate2y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_3y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRate3y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_this_year
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRateThisYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_from_establish
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double earningRateFromEstablish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.purchase_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String purchaseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.subscribe_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String subscribeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.redeem_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String redeemRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.manager_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double managerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.trustee_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double trusteeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.service_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double serviceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.first_buy_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double firstBuyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.purchase_limit_one_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double purchaseLimitOneDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.buy_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String buyComfirmDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.redeem_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String redeemComfirmDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.supplement_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double supplementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.positions_limit
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double positionsLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.min_remaining_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double minRemainingShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.min_purchase_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double minPurchaseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.min_redeem_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Double minRedeemShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.fund_code
     *
     * @return the value of fundData.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.fund_code
     *
     * @param fundCode the value for fundData.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.fund_name
     *
     * @return the value of fundData.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.fund_name
     *
     * @param fundName the value for fundData.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.date
     *
     * @return the value of fundData.date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.date
     *
     * @param date the value for fundData.date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.unit_net
     *
     * @return the value of fundData.unit_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getUnitNet() {
        return unitNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.unit_net
     *
     * @param unitNet the value for fundData.unit_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setUnitNet(Double unitNet) {
        this.unitNet = unitNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.accumulated_net
     *
     * @return the value of fundData.accumulated_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getAccumulatedNet() {
        return accumulatedNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.accumulated_net
     *
     * @param accumulatedNet the value for fundData.accumulated_net
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setAccumulatedNet(Double accumulatedNet) {
        this.accumulatedNet = accumulatedNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.growth_rate
     *
     * @return the value of fundData.growth_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getGrowthRate() {
        return growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.growth_rate
     *
     * @param growthRate the value for fundData.growth_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGrowthRate(Double growthRate) {
        this.growthRate = growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1w
     *
     * @return the value of fundData.earning_rate_1w
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate1w() {
        return earningRate1w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1w
     *
     * @param earningRate1w the value for fundData.earning_rate_1w
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate1w(Double earningRate1w) {
        this.earningRate1w = earningRate1w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1m
     *
     * @return the value of fundData.earning_rate_1m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate1m() {
        return earningRate1m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1m
     *
     * @param earningRate1m the value for fundData.earning_rate_1m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate1m(Double earningRate1m) {
        this.earningRate1m = earningRate1m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_3m
     *
     * @return the value of fundData.earning_rate_3m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate3m() {
        return earningRate3m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_3m
     *
     * @param earningRate3m the value for fundData.earning_rate_3m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate3m(Double earningRate3m) {
        this.earningRate3m = earningRate3m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_6m
     *
     * @return the value of fundData.earning_rate_6m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate6m() {
        return earningRate6m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_6m
     *
     * @param earningRate6m the value for fundData.earning_rate_6m
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate6m(Double earningRate6m) {
        this.earningRate6m = earningRate6m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1y
     *
     * @return the value of fundData.earning_rate_1y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate1y() {
        return earningRate1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1y
     *
     * @param earningRate1y the value for fundData.earning_rate_1y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate1y(Double earningRate1y) {
        this.earningRate1y = earningRate1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_2y
     *
     * @return the value of fundData.earning_rate_2y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate2y() {
        return earningRate2y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_2y
     *
     * @param earningRate2y the value for fundData.earning_rate_2y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate2y(Double earningRate2y) {
        this.earningRate2y = earningRate2y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_3y
     *
     * @return the value of fundData.earning_rate_3y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRate3y() {
        return earningRate3y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_3y
     *
     * @param earningRate3y the value for fundData.earning_rate_3y
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRate3y(Double earningRate3y) {
        this.earningRate3y = earningRate3y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_this_year
     *
     * @return the value of fundData.earning_rate_this_year
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRateThisYear() {
        return earningRateThisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_this_year
     *
     * @param earningRateThisYear the value for fundData.earning_rate_this_year
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRateThisYear(Double earningRateThisYear) {
        this.earningRateThisYear = earningRateThisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_from_establish
     *
     * @return the value of fundData.earning_rate_from_establish
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getEarningRateFromEstablish() {
        return earningRateFromEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_from_establish
     *
     * @param earningRateFromEstablish the value for fundData.earning_rate_from_establish
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEarningRateFromEstablish(Double earningRateFromEstablish) {
        this.earningRateFromEstablish = earningRateFromEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.purchase_rate
     *
     * @return the value of fundData.purchase_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getPurchaseRate() {
        return purchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.purchase_rate
     *
     * @param purchaseRate the value for fundData.purchase_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setPurchaseRate(String purchaseRate) {
        this.purchaseRate = purchaseRate == null ? null : purchaseRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.subscribe_rate
     *
     * @return the value of fundData.subscribe_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getSubscribeRate() {
        return subscribeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.subscribe_rate
     *
     * @param subscribeRate the value for fundData.subscribe_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setSubscribeRate(String subscribeRate) {
        this.subscribeRate = subscribeRate == null ? null : subscribeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.redeem_rate
     *
     * @return the value of fundData.redeem_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getRedeemRate() {
        return redeemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.redeem_rate
     *
     * @param redeemRate the value for fundData.redeem_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setRedeemRate(String redeemRate) {
        this.redeemRate = redeemRate == null ? null : redeemRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.manager_rate
     *
     * @return the value of fundData.manager_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getManagerRate() {
        return managerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.manager_rate
     *
     * @param managerRate the value for fundData.manager_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setManagerRate(Double managerRate) {
        this.managerRate = managerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.trustee_rate
     *
     * @return the value of fundData.trustee_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getTrusteeRate() {
        return trusteeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.trustee_rate
     *
     * @param trusteeRate the value for fundData.trustee_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setTrusteeRate(Double trusteeRate) {
        this.trusteeRate = trusteeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.service_rate
     *
     * @return the value of fundData.service_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getServiceRate() {
        return serviceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.service_rate
     *
     * @param serviceRate the value for fundData.service_rate
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setServiceRate(Double serviceRate) {
        this.serviceRate = serviceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.first_buy_amount
     *
     * @return the value of fundData.first_buy_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getFirstBuyAmount() {
        return firstBuyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.first_buy_amount
     *
     * @param firstBuyAmount the value for fundData.first_buy_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFirstBuyAmount(Double firstBuyAmount) {
        this.firstBuyAmount = firstBuyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.purchase_limit_one_day
     *
     * @return the value of fundData.purchase_limit_one_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getPurchaseLimitOneDay() {
        return purchaseLimitOneDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.purchase_limit_one_day
     *
     * @param purchaseLimitOneDay the value for fundData.purchase_limit_one_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setPurchaseLimitOneDay(Double purchaseLimitOneDay) {
        this.purchaseLimitOneDay = purchaseLimitOneDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.buy_comfirm_day
     *
     * @return the value of fundData.buy_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getBuyComfirmDay() {
        return buyComfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.buy_comfirm_day
     *
     * @param buyComfirmDay the value for fundData.buy_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setBuyComfirmDay(String buyComfirmDay) {
        this.buyComfirmDay = buyComfirmDay == null ? null : buyComfirmDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.redeem_comfirm_day
     *
     * @return the value of fundData.redeem_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getRedeemComfirmDay() {
        return redeemComfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.redeem_comfirm_day
     *
     * @param redeemComfirmDay the value for fundData.redeem_comfirm_day
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setRedeemComfirmDay(String redeemComfirmDay) {
        this.redeemComfirmDay = redeemComfirmDay == null ? null : redeemComfirmDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.supplement_amount
     *
     * @return the value of fundData.supplement_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getSupplementAmount() {
        return supplementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.supplement_amount
     *
     * @param supplementAmount the value for fundData.supplement_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setSupplementAmount(Double supplementAmount) {
        this.supplementAmount = supplementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.positions_limit
     *
     * @return the value of fundData.positions_limit
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getPositionsLimit() {
        return positionsLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.positions_limit
     *
     * @param positionsLimit the value for fundData.positions_limit
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setPositionsLimit(Double positionsLimit) {
        this.positionsLimit = positionsLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.min_remaining_share
     *
     * @return the value of fundData.min_remaining_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getMinRemainingShare() {
        return minRemainingShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.min_remaining_share
     *
     * @param minRemainingShare the value for fundData.min_remaining_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setMinRemainingShare(Double minRemainingShare) {
        this.minRemainingShare = minRemainingShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.min_purchase_amount
     *
     * @return the value of fundData.min_purchase_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getMinPurchaseAmount() {
        return minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.min_purchase_amount
     *
     * @param minPurchaseAmount the value for fundData.min_purchase_amount
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setMinPurchaseAmount(Double minPurchaseAmount) {
        this.minPurchaseAmount = minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.min_redeem_share
     *
     * @return the value of fundData.min_redeem_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Double getMinRedeemShare() {
        return minRedeemShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.min_redeem_share
     *
     * @param minRedeemShare the value for fundData.min_redeem_share
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setMinRedeemShare(Double minRedeemShare) {
        this.minRedeemShare = minRedeemShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.ext_info
     *
     * @return the value of fundData.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.ext_info
     *
     * @param extInfo the value for fundData.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.gmt_create
     *
     * @return the value of fundData.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.gmt_create
     *
     * @param gmtCreate the value for fundData.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.gmt_modified
     *
     * @return the value of fundData.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.gmt_modified
     *
     * @param gmtModified the value for fundData.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}