package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class FundManagerDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_id
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.fund_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.service_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Integer serviceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.assets_scale
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String assetsScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.best_return_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String bestReturnNow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.best_return_code_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String bestReturnCodeNow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.best_return_name_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String bestReturnNameNow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.best_return_history
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String bestReturnHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.start_working_time
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date startWorkingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_introduction
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String managerIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_id
     *
     * @return the value of fundManager.manager_id
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_id
     *
     * @param managerId the value for fundManager.manager_id
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_name
     *
     * @return the value of fundManager.manager_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_name
     *
     * @param managerName the value for fundManager.manager_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.company_code
     *
     * @return the value of fundManager.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.company_code
     *
     * @param companyCode the value for fundManager.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.company_name
     *
     * @return the value of fundManager.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.company_name
     *
     * @param companyName the value for fundManager.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.fund_codes
     *
     * @return the value of fundManager.fund_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundCodes() {
        return fundCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.fund_codes
     *
     * @param fundCodes the value for fundManager.fund_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundCodes(String fundCodes) {
        this.fundCodes = fundCodes == null ? null : fundCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.service_date
     *
     * @return the value of fundManager.service_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Integer getServiceDate() {
        return serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.service_date
     *
     * @param serviceDate the value for fundManager.service_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setServiceDate(Integer serviceDate) {
        this.serviceDate = serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.assets_scale
     *
     * @return the value of fundManager.assets_scale
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getAssetsScale() {
        return assetsScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.assets_scale
     *
     * @param assetsScale the value for fundManager.assets_scale
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setAssetsScale(String assetsScale) {
        this.assetsScale = assetsScale == null ? null : assetsScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.best_return_now
     *
     * @return the value of fundManager.best_return_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getBestReturnNow() {
        return bestReturnNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.best_return_now
     *
     * @param bestReturnNow the value for fundManager.best_return_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setBestReturnNow(String bestReturnNow) {
        this.bestReturnNow = bestReturnNow == null ? null : bestReturnNow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.best_return_code_now
     *
     * @return the value of fundManager.best_return_code_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getBestReturnCodeNow() {
        return bestReturnCodeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.best_return_code_now
     *
     * @param bestReturnCodeNow the value for fundManager.best_return_code_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setBestReturnCodeNow(String bestReturnCodeNow) {
        this.bestReturnCodeNow = bestReturnCodeNow == null ? null : bestReturnCodeNow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.best_return_name_now
     *
     * @return the value of fundManager.best_return_name_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getBestReturnNameNow() {
        return bestReturnNameNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.best_return_name_now
     *
     * @param bestReturnNameNow the value for fundManager.best_return_name_now
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setBestReturnNameNow(String bestReturnNameNow) {
        this.bestReturnNameNow = bestReturnNameNow == null ? null : bestReturnNameNow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.best_return_history
     *
     * @return the value of fundManager.best_return_history
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getBestReturnHistory() {
        return bestReturnHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.best_return_history
     *
     * @param bestReturnHistory the value for fundManager.best_return_history
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setBestReturnHistory(String bestReturnHistory) {
        this.bestReturnHistory = bestReturnHistory == null ? null : bestReturnHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.start_working_time
     *
     * @return the value of fundManager.start_working_time
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getStartWorkingTime() {
        return startWorkingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.start_working_time
     *
     * @param startWorkingTime the value for fundManager.start_working_time
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setStartWorkingTime(Date startWorkingTime) {
        this.startWorkingTime = startWorkingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_introduction
     *
     * @return the value of fundManager.manager_introduction
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getManagerIntroduction() {
        return managerIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_introduction
     *
     * @param managerIntroduction the value for fundManager.manager_introduction
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setManagerIntroduction(String managerIntroduction) {
        this.managerIntroduction = managerIntroduction == null ? null : managerIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.ext_info
     *
     * @return the value of fundManager.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.ext_info
     *
     * @param extInfo the value for fundManager.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.gmt_create
     *
     * @return the value of fundManager.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.gmt_create
     *
     * @param gmtCreate the value for fundManager.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.gmt_modified
     *
     * @return the value of fundManager.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.gmt_modified
     *
     * @param gmtModified the value for fundManager.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}