package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class FundArchiveDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.fund_name_abbr
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundNameAbbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.fund_name_pinyin
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundNamePinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.fund_type
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String fundType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.stock_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String stockCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.zq_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String zqCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.establish_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date establishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.issue_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date issueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.manager_ids
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String managerIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.custodian
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String custodian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.performance_baseline
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String performanceBaseline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.tracking_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String trackingTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.investment_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String investmentTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.investment_concept
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String investmentConcept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.investment_scope
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String investmentScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.investment_strategy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String investmentStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.dividend_policy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String dividendPolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.risk_return_characteristics
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String riskReturnCharacteristics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundArchive.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.fund_code
     *
     * @return the value of fundArchive.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.fund_code
     *
     * @param fundCode the value for fundArchive.fund_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.fund_name
     *
     * @return the value of fundArchive.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.fund_name
     *
     * @param fundName the value for fundArchive.fund_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.fund_name_abbr
     *
     * @return the value of fundArchive.fund_name_abbr
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundNameAbbr() {
        return fundNameAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.fund_name_abbr
     *
     * @param fundNameAbbr the value for fundArchive.fund_name_abbr
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundNameAbbr(String fundNameAbbr) {
        this.fundNameAbbr = fundNameAbbr == null ? null : fundNameAbbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.fund_name_pinyin
     *
     * @return the value of fundArchive.fund_name_pinyin
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundNamePinyin() {
        return fundNamePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.fund_name_pinyin
     *
     * @param fundNamePinyin the value for fundArchive.fund_name_pinyin
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundNamePinyin(String fundNamePinyin) {
        this.fundNamePinyin = fundNamePinyin == null ? null : fundNamePinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.fund_type
     *
     * @return the value of fundArchive.fund_type
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.fund_type
     *
     * @param fundType the value for fundArchive.fund_type
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setFundType(String fundType) {
        this.fundType = fundType == null ? null : fundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.stock_codes
     *
     * @return the value of fundArchive.stock_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getStockCodes() {
        return stockCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.stock_codes
     *
     * @param stockCodes the value for fundArchive.stock_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setStockCodes(String stockCodes) {
        this.stockCodes = stockCodes == null ? null : stockCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.zq_codes
     *
     * @return the value of fundArchive.zq_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getZqCodes() {
        return zqCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.zq_codes
     *
     * @param zqCodes the value for fundArchive.zq_codes
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setZqCodes(String zqCodes) {
        this.zqCodes = zqCodes == null ? null : zqCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.establish_date
     *
     * @return the value of fundArchive.establish_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.establish_date
     *
     * @param establishDate the value for fundArchive.establish_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.issue_date
     *
     * @return the value of fundArchive.issue_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.issue_date
     *
     * @param issueDate the value for fundArchive.issue_date
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.company_code
     *
     * @return the value of fundArchive.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.company_code
     *
     * @param companyCode the value for fundArchive.company_code
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.company_name
     *
     * @return the value of fundArchive.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.company_name
     *
     * @param companyName the value for fundArchive.company_name
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.manager_ids
     *
     * @return the value of fundArchive.manager_ids
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getManagerIds() {
        return managerIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.manager_ids
     *
     * @param managerIds the value for fundArchive.manager_ids
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setManagerIds(String managerIds) {
        this.managerIds = managerIds == null ? null : managerIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.custodian
     *
     * @return the value of fundArchive.custodian
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getCustodian() {
        return custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.custodian
     *
     * @param custodian the value for fundArchive.custodian
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setCustodian(String custodian) {
        this.custodian = custodian == null ? null : custodian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.performance_baseline
     *
     * @return the value of fundArchive.performance_baseline
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getPerformanceBaseline() {
        return performanceBaseline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.performance_baseline
     *
     * @param performanceBaseline the value for fundArchive.performance_baseline
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setPerformanceBaseline(String performanceBaseline) {
        this.performanceBaseline = performanceBaseline == null ? null : performanceBaseline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.tracking_target
     *
     * @return the value of fundArchive.tracking_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getTrackingTarget() {
        return trackingTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.tracking_target
     *
     * @param trackingTarget the value for fundArchive.tracking_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setTrackingTarget(String trackingTarget) {
        this.trackingTarget = trackingTarget == null ? null : trackingTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.investment_target
     *
     * @return the value of fundArchive.investment_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getInvestmentTarget() {
        return investmentTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.investment_target
     *
     * @param investmentTarget the value for fundArchive.investment_target
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setInvestmentTarget(String investmentTarget) {
        this.investmentTarget = investmentTarget == null ? null : investmentTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.investment_concept
     *
     * @return the value of fundArchive.investment_concept
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getInvestmentConcept() {
        return investmentConcept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.investment_concept
     *
     * @param investmentConcept the value for fundArchive.investment_concept
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setInvestmentConcept(String investmentConcept) {
        this.investmentConcept = investmentConcept == null ? null : investmentConcept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.investment_scope
     *
     * @return the value of fundArchive.investment_scope
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getInvestmentScope() {
        return investmentScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.investment_scope
     *
     * @param investmentScope the value for fundArchive.investment_scope
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setInvestmentScope(String investmentScope) {
        this.investmentScope = investmentScope == null ? null : investmentScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.investment_strategy
     *
     * @return the value of fundArchive.investment_strategy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getInvestmentStrategy() {
        return investmentStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.investment_strategy
     *
     * @param investmentStrategy the value for fundArchive.investment_strategy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setInvestmentStrategy(String investmentStrategy) {
        this.investmentStrategy = investmentStrategy == null ? null : investmentStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.dividend_policy
     *
     * @return the value of fundArchive.dividend_policy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getDividendPolicy() {
        return dividendPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.dividend_policy
     *
     * @param dividendPolicy the value for fundArchive.dividend_policy
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setDividendPolicy(String dividendPolicy) {
        this.dividendPolicy = dividendPolicy == null ? null : dividendPolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.risk_return_characteristics
     *
     * @return the value of fundArchive.risk_return_characteristics
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getRiskReturnCharacteristics() {
        return riskReturnCharacteristics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.risk_return_characteristics
     *
     * @param riskReturnCharacteristics the value for fundArchive.risk_return_characteristics
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setRiskReturnCharacteristics(String riskReturnCharacteristics) {
        this.riskReturnCharacteristics = riskReturnCharacteristics == null ? null : riskReturnCharacteristics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.ext_info
     *
     * @return the value of fundArchive.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.ext_info
     *
     * @param extInfo the value for fundArchive.ext_info
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.gmt_create
     *
     * @return the value of fundArchive.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.gmt_create
     *
     * @param gmtCreate the value for fundArchive.gmt_create
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundArchive.gmt_modified
     *
     * @return the value of fundArchive.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundArchive.gmt_modified
     *
     * @param gmtModified the value for fundArchive.gmt_modified
     *
     * @mbg.generated Fri Jan 31 21:56:44 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}