package com.sdu.fund.common.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private String payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.user_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.order_amount
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_channel
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private String payChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.pay_status
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.gmt_create
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.gmt_modified
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_order_id
     *
     * @return the value of payment.pay_order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_order_id
     *
     * @param payOrderId the value for payment.pay_order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.order_id
     *
     * @return the value of payment.order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.order_id
     *
     * @param orderId the value for payment.order_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.user_id
     *
     * @return the value of payment.user_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.user_id
     *
     * @param userId the value for payment.user_id
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.order_amount
     *
     * @return the value of payment.order_amount
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.order_amount
     *
     * @param orderAmount the value for payment.order_amount
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_channel
     *
     * @return the value of payment.pay_channel
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_channel
     *
     * @param payChannel the value for payment.pay_channel
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.pay_status
     *
     * @return the value of payment.pay_status
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.pay_status
     *
     * @param payStatus the value for payment.pay_status
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.gmt_create
     *
     * @return the value of payment.gmt_create
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.gmt_create
     *
     * @param gmtCreate the value for payment.gmt_create
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.gmt_modified
     *
     * @return the value of payment.gmt_modified
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.gmt_modified
     *
     * @param gmtModified the value for payment.gmt_modified
     *
     * @mbg.generated Sun Feb 16 21:18:34 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}