package com.sdu.fund.common.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeOrderDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private String tradeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.user_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.fund_code
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.fund_name
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private BigDecimal tradeOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.fee
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.real_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private BigDecimal realAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_type
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private String tradeOrderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_status
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private String tradeOrderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_share
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private BigDecimal tradeOrderShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.tradeOrder_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date tradeOrderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.pay_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.share_confirm_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date shareConfirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.arrival_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.canel_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date canelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.gmt_create
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeOrder.gmt_modified
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_id
     *
     * @return the value of tradeOrder.tradeOrder_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public String getTradeOrderId() {
        return tradeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_id
     *
     * @param tradeOrderId the value for tradeOrder.tradeOrder_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderId(String tradeOrderId) {
        this.tradeOrderId = tradeOrderId == null ? null : tradeOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.user_id
     *
     * @return the value of tradeOrder.user_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.user_id
     *
     * @param userId the value for tradeOrder.user_id
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.fund_code
     *
     * @return the value of tradeOrder.fund_code
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.fund_code
     *
     * @param fundCode the value for tradeOrder.fund_code
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.fund_name
     *
     * @return the value of tradeOrder.fund_name
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.fund_name
     *
     * @param fundName the value for tradeOrder.fund_name
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_amount
     *
     * @return the value of tradeOrder.tradeOrder_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public BigDecimal getTradeOrderAmount() {
        return tradeOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_amount
     *
     * @param tradeOrderAmount the value for tradeOrder.tradeOrder_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderAmount(BigDecimal tradeOrderAmount) {
        this.tradeOrderAmount = tradeOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.fee
     *
     * @return the value of tradeOrder.fee
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.fee
     *
     * @param fee the value for tradeOrder.fee
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.real_amount
     *
     * @return the value of tradeOrder.real_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public BigDecimal getRealAmount() {
        return realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.real_amount
     *
     * @param realAmount the value for tradeOrder.real_amount
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_type
     *
     * @return the value of tradeOrder.tradeOrder_type
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public String getTradeOrderType() {
        return tradeOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_type
     *
     * @param tradeOrderType the value for tradeOrder.tradeOrder_type
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderType(String tradeOrderType) {
        this.tradeOrderType = tradeOrderType == null ? null : tradeOrderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_status
     *
     * @return the value of tradeOrder.tradeOrder_status
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public String getTradeOrderStatus() {
        return tradeOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_status
     *
     * @param tradeOrderStatus the value for tradeOrder.tradeOrder_status
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderStatus(String tradeOrderStatus) {
        this.tradeOrderStatus = tradeOrderStatus == null ? null : tradeOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_share
     *
     * @return the value of tradeOrder.tradeOrder_share
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public BigDecimal getTradeOrderShare() {
        return tradeOrderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_share
     *
     * @param tradeOrderShare the value for tradeOrder.tradeOrder_share
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderShare(BigDecimal tradeOrderShare) {
        this.tradeOrderShare = tradeOrderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.tradeOrder_time
     *
     * @return the value of tradeOrder.tradeOrder_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getTradeOrderTime() {
        return tradeOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.tradeOrder_time
     *
     * @param tradeOrderTime the value for tradeOrder.tradeOrder_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setTradeOrderTime(Date tradeOrderTime) {
        this.tradeOrderTime = tradeOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.pay_time
     *
     * @return the value of tradeOrder.pay_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.pay_time
     *
     * @param payTime the value for tradeOrder.pay_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.share_confirm_time
     *
     * @return the value of tradeOrder.share_confirm_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getShareConfirmTime() {
        return shareConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.share_confirm_time
     *
     * @param shareConfirmTime the value for tradeOrder.share_confirm_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setShareConfirmTime(Date shareConfirmTime) {
        this.shareConfirmTime = shareConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.arrival_time
     *
     * @return the value of tradeOrder.arrival_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.arrival_time
     *
     * @param arrivalTime the value for tradeOrder.arrival_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.canel_time
     *
     * @return the value of tradeOrder.canel_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getCanelTime() {
        return canelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.canel_time
     *
     * @param canelTime the value for tradeOrder.canel_time
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setCanelTime(Date canelTime) {
        this.canelTime = canelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.gmt_create
     *
     * @return the value of tradeOrder.gmt_create
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.gmt_create
     *
     * @param gmtCreate the value for tradeOrder.gmt_create
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeOrder.gmt_modified
     *
     * @return the value of tradeOrder.gmt_modified
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeOrder.gmt_modified
     *
     * @param gmtModified the value for tradeOrder.gmt_modified
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}