package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class TradeOrderFlowDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.flow_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Long flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.initiator
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String initiator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.flow_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date flowTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.valid
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order_flow.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.flow_id
     *
     * @return the value of trade_order_flow.flow_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.flow_id
     *
     * @param flowId the value for trade_order_flow.flow_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.order_id
     *
     * @return the value of trade_order_flow.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.order_id
     *
     * @param orderId the value for trade_order_flow.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.pay_order_id
     *
     * @return the value of trade_order_flow.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.pay_order_id
     *
     * @param payOrderId the value for trade_order_flow.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.user_id
     *
     * @return the value of trade_order_flow.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.user_id
     *
     * @param userId the value for trade_order_flow.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.type
     *
     * @return the value of trade_order_flow.type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.type
     *
     * @param type the value for trade_order_flow.type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.initiator
     *
     * @return the value of trade_order_flow.initiator
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.initiator
     *
     * @param initiator the value for trade_order_flow.initiator
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setInitiator(String initiator) {
        this.initiator = initiator == null ? null : initiator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.flow_time
     *
     * @return the value of trade_order_flow.flow_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getFlowTime() {
        return flowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.flow_time
     *
     * @param flowTime the value for trade_order_flow.flow_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFlowTime(Date flowTime) {
        this.flowTime = flowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.valid
     *
     * @return the value of trade_order_flow.valid
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.valid
     *
     * @param valid the value for trade_order_flow.valid
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.gmt_create
     *
     * @return the value of trade_order_flow.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.gmt_create
     *
     * @param gmtCreate the value for trade_order_flow.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order_flow.gmt_modified
     *
     * @return the value of trade_order_flow.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order_flow.gmt_modified
     *
     * @param gmtModified the value for trade_order_flow.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}