package com.sdu.fund.common.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeOrderDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.idempotent_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String idempotentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.fund_code
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.fund_name
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.fee
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.fee_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private BigDecimal feeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.real_pay_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private BigDecimal realPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_status
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_share
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private BigDecimal orderShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.order_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.pay_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.share_confirm_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date shareConfirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.arrival_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.canel_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date canelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.ext_info
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_id
     *
     * @return the value of trade_order.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_id
     *
     * @param orderId the value for trade_order.order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.user_id
     *
     * @return the value of trade_order.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.user_id
     *
     * @param userId the value for trade_order.user_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.idempotent_id
     *
     * @return the value of trade_order.idempotent_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getIdempotentId() {
        return idempotentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.idempotent_id
     *
     * @param idempotentId the value for trade_order.idempotent_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setIdempotentId(String idempotentId) {
        this.idempotentId = idempotentId == null ? null : idempotentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.fund_code
     *
     * @return the value of trade_order.fund_code
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.fund_code
     *
     * @param fundCode the value for trade_order.fund_code
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.fund_name
     *
     * @return the value of trade_order.fund_name
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.fund_name
     *
     * @param fundName the value for trade_order.fund_name
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_amount
     *
     * @return the value of trade_order.order_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_amount
     *
     * @param orderAmount the value for trade_order.order_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.fee
     *
     * @return the value of trade_order.fee
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.fee
     *
     * @param fee the value for trade_order.fee
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.fee_amount
     *
     * @return the value of trade_order.fee_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.fee_amount
     *
     * @param feeAmount the value for trade_order.fee_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.real_pay_amount
     *
     * @return the value of trade_order.real_pay_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public BigDecimal getRealPayAmount() {
        return realPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.real_pay_amount
     *
     * @param realPayAmount the value for trade_order.real_pay_amount
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setRealPayAmount(BigDecimal realPayAmount) {
        this.realPayAmount = realPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_type
     *
     * @return the value of trade_order.order_type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_type
     *
     * @param orderType the value for trade_order.order_type
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_status
     *
     * @return the value of trade_order.order_status
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_status
     *
     * @param orderStatus the value for trade_order.order_status
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_share
     *
     * @return the value of trade_order.order_share
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public BigDecimal getOrderShare() {
        return orderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_share
     *
     * @param orderShare the value for trade_order.order_share
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderShare(BigDecimal orderShare) {
        this.orderShare = orderShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.order_time
     *
     * @return the value of trade_order.order_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.order_time
     *
     * @param orderTime the value for trade_order.order_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.pay_time
     *
     * @return the value of trade_order.pay_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.pay_time
     *
     * @param payTime the value for trade_order.pay_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.pay_order_id
     *
     * @return the value of trade_order.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.pay_order_id
     *
     * @param payOrderId the value for trade_order.pay_order_id
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.share_confirm_time
     *
     * @return the value of trade_order.share_confirm_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getShareConfirmTime() {
        return shareConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.share_confirm_time
     *
     * @param shareConfirmTime the value for trade_order.share_confirm_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setShareConfirmTime(Date shareConfirmTime) {
        this.shareConfirmTime = shareConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.arrival_time
     *
     * @return the value of trade_order.arrival_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.arrival_time
     *
     * @param arrivalTime the value for trade_order.arrival_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.canel_time
     *
     * @return the value of trade_order.canel_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getCanelTime() {
        return canelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.canel_time
     *
     * @param canelTime the value for trade_order.canel_time
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setCanelTime(Date canelTime) {
        this.canelTime = canelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.ext_info
     *
     * @return the value of trade_order.ext_info
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.ext_info
     *
     * @param extInfo the value for trade_order.ext_info
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmt_create
     *
     * @return the value of trade_order.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmt_create
     *
     * @param gmtCreate the value for trade_order.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmt_modified
     *
     * @return the value of trade_order.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmt_modified
     *
     * @param gmtModified the value for trade_order.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}