package com.sdu.fund.common.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccountDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.user_id
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.totol_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private BigDecimal totolAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.avail_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private BigDecimal availAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.freeze_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private BigDecimal freezeAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.type
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.status
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.check_value
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private String checkValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.gmt_create
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.gmt_modified
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.user_id
     *
     * @return the value of user_account.user_id
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.user_id
     *
     * @param userId the value for user_account.user_id
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.totol_account
     *
     * @return the value of user_account.totol_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public BigDecimal getTotolAccount() {
        return totolAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.totol_account
     *
     * @param totolAccount the value for user_account.totol_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setTotolAccount(BigDecimal totolAccount) {
        this.totolAccount = totolAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.avail_account
     *
     * @return the value of user_account.avail_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public BigDecimal getAvailAccount() {
        return availAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.avail_account
     *
     * @param availAccount the value for user_account.avail_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setAvailAccount(BigDecimal availAccount) {
        this.availAccount = availAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.freeze_account
     *
     * @return the value of user_account.freeze_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public BigDecimal getFreezeAccount() {
        return freezeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.freeze_account
     *
     * @param freezeAccount the value for user_account.freeze_account
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setFreezeAccount(BigDecimal freezeAccount) {
        this.freezeAccount = freezeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.type
     *
     * @return the value of user_account.type
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.type
     *
     * @param type the value for user_account.type
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.status
     *
     * @return the value of user_account.status
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.status
     *
     * @param status the value for user_account.status
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.check_value
     *
     * @return the value of user_account.check_value
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public String getCheckValue() {
        return checkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.check_value
     *
     * @param checkValue the value for user_account.check_value
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setCheckValue(String checkValue) {
        this.checkValue = checkValue == null ? null : checkValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.gmt_create
     *
     * @return the value of user_account.gmt_create
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.gmt_create
     *
     * @param gmtCreate the value for user_account.gmt_create
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.gmt_modified
     *
     * @return the value of user_account.gmt_modified
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.gmt_modified
     *
     * @param gmtModified the value for user_account.gmt_modified
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}