package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.HoldPositionDo;

public interface HoldPositionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    int insert(HoldPositionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    int insertSelective(HoldPositionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    HoldPositionDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    int updateByPrimaryKeySelective(HoldPositionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Wed Mar 04 13:17:20 CST 2020
     */
    int updateByPrimaryKey(HoldPositionDo record);
}