package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.HoldPositionsDo;

public interface HoldPositionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int insert(HoldPositionsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int insertSelective(HoldPositionsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    HoldPositionsDo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int updateByPrimaryKeySelective(HoldPositionsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold_positions
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int updateByPrimaryKey(HoldPositionsDo record);
}