package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.PaymentDo;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int deleteByPrimaryKey(String payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insert(PaymentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insertSelective(PaymentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    PaymentDo selectByPrimaryKey(String payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKeySelective(PaymentDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKey(PaymentDo record);
}