package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.TradeOrderFlowDo;

public interface TradeOrderFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int deleteByPrimaryKey(String flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int insert(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int insertSelective(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    TradeOrderFlowDo selectByPrimaryKey(String flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int updateByPrimaryKeySelective(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Mon Feb 17 16:06:31 CST 2020
     */
    int updateByPrimaryKey(TradeOrderFlowDo record);
}