package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.TradeOrderFlowDo;

public interface TradeOrderFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int deleteByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insert(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insertSelective(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    TradeOrderFlowDo selectByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKeySelective(TradeOrderFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKey(TradeOrderFlowDo record);
}