package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.UserAccountFlowDo;

public interface UserAccountFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int deleteByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insert(UserAccountFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int insertSelective(UserAccountFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    UserAccountFlowDo selectByPrimaryKey(Long flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKeySelective(UserAccountFlowDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_flow
     *
     * @mbg.generated Thu Feb 20 20:41:19 CST 2020
     */
    int updateByPrimaryKey(UserAccountFlowDo record);
}