package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.UserTokenDo;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    int deleteByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    int insert(UserTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    int insertSelective(UserTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    UserTokenDo selectByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    int updateByPrimaryKeySelective(UserTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userToken
     *
     * @mbg.generated Sat Feb 15 13:29:01 CST 2020
     */
    int updateByPrimaryKey(UserTokenDo record);
}